version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db

  nx-todolist-backend:
    build: .
    ports:
      - 4000:3000
      - 4311:4311
    environment:
      DEV_PLATFORM: DOCKER
      PORT: 3000
      MONGODB_URI: mongodb://root:root@localhost:27017/?authMechanism=DEFAULT
      DB_NAME: nx-todolist
    depends_on:
      - mongo
      
volumes:
  mongo_data: {}
