version: '3.3'

services:
  mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27010:27017
    volumes:
      - ./mongo_data:/data/db
      
volumes:
  mono-node-modules: null
