version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27010:27017
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data: {}
