version: '3.3'

services:
  mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27010:27017
    volumes:
      - ./mongo_data:/data/db

  nx-todolist-backend:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: nx run nx-todolist-backend:serve:development:docker
    ports:
      - 4310:3333
      - 4311:4311
      
volumes:
  mono-node-modules: null
